### ISSUE TITLE
seglength vs lengthofseq

### ISSUE THREAD

**Issue by jychoilab** [PhHermann/LDJump#19]
Hi developers

Could you clarify what the difference of the two is? Seems like its necessary to have both values when you use a VCF file. Is lengthofseq basically the length of the entire chromosome? Assuming one is trying to estimate the recombination rate across a single chromosome.
I've read the manual and although it says

> an integer value describing the length of the sequence (Only required when run- ning LDJump with VCF-Files). It is used to compute the number of segments and to loop through each segment.

its still confusing to me what the "sequence" represent.

Thank you.

**Comment by fardokhtsadat** [comment]
Hello!

We are sorry for the late response. Thank you for taking interest into LDJump. 

The segLength is a paramater that is required in both cases: either when you use FASTA-files as input-format or VCF-files as input. The segLength argument specifies how long each segment in your analysis should be. If it is set, for example, to 1kb, then LDJump will be running its summary-statistics one 1kb segments. The user can vary the segment-length depending on how much SNP-information there is in the data. 

The lengthofseq argument, on the other hand, is a parameter that is used if VCF-files are given as input. The lengthofseq specifies how long the genomic region is that you are analyzing. If someone, for example, is trying to estimate recombination rates along a chromosome, lengthofseq will be the length of that chromosome. Another example would be if I had a VCF-file containing SNP-information only for 2 million base-pair of some genomic region, in this case, the lengthofseq argument is set to 2 million. 

We hope we could clarify the difference between the two parameters. In case of further questions please feel free to ask.

**Comment by jychoilab** [comment]
Thanks for the clarification!
