### ISSUE TITLE
Error with example

### ISSUE THREAD

**Issue by wbooker** [PhHermann/LDJump#7]
Hi, I'm trying to run the example and am unable to. Hoping you could help.

Here's the code: 
results = LDJump("/home/wbooker/Downloads/HatLandscapeN16Len1000000Nrhs15_th0.01_540_1.fa", alpha = 0.05, segLength = 1000, pathPhi = "/home/wbooker/Downloads/PhiPack", pathLDhat = "/home/wbooker/Downloads/LDhat-master", format = "fasta", refName = NULL)

Here's the error:
sh: 1: /programs/PhiPack/Phi: not found
Error in strsplit(system(paste0("grep 'Value of maximum breakpoint is:' ",  : 
  subscript out of bounds
In addition: Warning message:
running command 'grep 'Value of maximum breakpoint is:' Phi1.log' had status 1 

Thanks!

**Comment by PhHermann** [comment]
Hi, 

thanks for your feedback. I think that this error results from the parameter _pathPhi_. Please try to run the following code (added **/Phi** to _pathPhi_): 
`results = LDJump("/home/wbooker/Downloads/HatLandscapeN16Len1000000Nrhs15_th0.01_540_1.fa", alpha = 0.05, segLength = 1000, pathPhi = "/home/wbooker/Downloads/PhiPack/Phi", pathLDhat = "/home/wbooker/Downloads/LDhat-master", format = "fasta", refName = NULL)`.

In case there are still problems running the example, please let me know. 

Best wishes, 
Philipp

**Comment by wbooker** [comment]
Hey Philipp,

Still having the same issue.

-Will

**Comment by PhHermann** [comment]
Hi Will, 
I fixed _pathPhi_ in the code and uploaded an update of **LDJump**. Please download the most recent version and let me know whether you could run the example. 
Thanks a lot for your feedback. 
Philipp

**Comment by wbooker** [comment]
Hi Philipp,

Thanks, that error seemed to get fixed. I did have an issue at the end of the run, however. Posted below.

[1] "100.1% of Segments calculated"
Error in FUN(X[[i]], ...) : no lines available in input
In addition: Warning messages:
1: In getPhi(seqName = paste0("tmpfile", x, out, ".fa"), pathPhi = pathPhi,  :
  NAs introduced by coercion
2: In getPhi(seqName = paste0("tmpfile", x, out, ".fa"), pathPhi = pathPhi,  :
  NAs introduced by coercion
3: In getPhi(seqName = paste0("tmpfile", x, out, ".fa"), pathPhi = pathPhi,  :
  NAs introduced by coercion
4: In getPhi(seqName = paste0("tmpfile", x, out, ".fa"), pathPhi = pathPhi,  :
  NAs introduced by coercion
5: In getPhi(seqName = paste0("tmpfile", x, out, ".fa"), pathPhi = pathPhi,  :
  NAs introduced by coercion
6: In getPhi(seqName = paste0("tmpfile", x, out, ".fa"), pathPhi = pathPhi,  :
  NAs introduced by coercion

-Will

**Comment by PhHermann** [comment]
Hi Will, 

I successfully tested the update of **LDJump** on my machine. Could you please check whether there are any remaining temp-files in the working directory and - in case yes - delete them before restarting **LDJump**. It seems that **LDJump** cannot read from either a sequence or one of the internally created tempfiles correctly. 

Philipp

**Comment by wbooker** [comment]
Hi Philipp,

I removed the files but it seems like something isn't resetting properly. The "x% of segments calculated" bit seems to keep building on itself even after I restart R, clear the workspace, or remove temp files. Example below:

> results2 = LDJump("/home/wbooker/Downloads/LDJump_Temp/HatLandscapeN16Len1000000Nrhs15_th0.01_1000_1.fa", alpha = 0.05, segLength = 1000, pathPhi = "/home/wbooker/Downloads/PhiPack/Phi", pathLDhat = "/home/wbooker/Downloads/LDhat-master", format = "fasta", refName = NULL)

Haplotypes extracted from: samp 

    Number of haplotypes: 12 
         Sequence length: 1000 

Haplotype labels and frequencies:

   I   II  III   IV    V   VI  VII VIII   IX    X   XI  XII 
   1    2    1    1    1    1    1    2    2    1    1    2 
[1] "217% of Segments calculated"

**Comment by wbooker** [comment]
Hey Philipp,

That seemed to help. Getting a new error now though.

Error in Predict.matrix.tprs.smooth(object, dk$data) : 
  object 'C_predict_tprs' not found
In addition: Warning messages:
1: In getPhi(seqName = paste0("tmpfile", x, out, ".fa"), pathPhi = pathPhi,  :
  NAs introduced by coercion
2: In getPhi(seqName = paste0("tmpfile", x, out, ".fa"), pathPhi = pathPhi,  :
  NAs introduced by coercion

**Comment by dingmengting-sys** [comment]
Hi, @wbooker 
I got the same error, and could you please share a solution to this problem?
Thanks!
